"""Tests for GitLab tools — requires live GitLab token and project in .env."""

import pytest

pytestmark = pytest.mark.asyncio


async def test_search_recent_commits_structure():
    """search_recent_commits returns a dict with 'commits' list."""
    from agent.tools.gitlab_tools import search_recent_commits

    result = await search_recent_commits(hours_back=72)

    assert isinstance(result, dict)
    assert "commits" in result
    assert isinstance(result["commits"], list)


async def test_search_recent_commits_fields():
    """Each commit entry has required fields."""
    from agent.tools.gitlab_tools import search_recent_commits

    result = await search_recent_commits(hours_back=720)  # 30 days to catch any commit

    if result["commits"]:
        commit = result["commits"][0]
        assert "sha" in commit
        assert "title" in commit
        assert "author" in commit
        assert "created_at" in commit
        assert "web_url" in commit
        assert "gitlab.com" in commit["web_url"]


async def test_search_recent_commits_with_file_path():
    """File path filter does not crash — returns list (may be empty)."""
    from agent.tools.gitlab_tools import search_recent_commits

    result = await search_recent_commits(file_path="README.md", hours_back=720)

    assert "commits" in result
    assert isinstance(result["commits"], list)


async def test_search_recent_commits_respects_max_results():
    """max_results cap is applied."""
    from agent.tools.gitlab_tools import search_recent_commits

    result = await search_recent_commits(hours_back=720, max_results=2)

    assert len(result["commits"]) <= 2


async def test_find_mr_for_commit_invalid_sha_returns_not_found():
    """A bogus SHA should return found=False, not raise."""
    from agent.tools.gitlab_tools import find_mr_for_commit

    result = await find_mr_for_commit("0000000000000000000000000000000000000000")

    assert isinstance(result, dict)
    assert result.get("found") is False


async def test_find_mr_for_commit_structure_when_not_found():
    """find_mr_for_commit always returns a dict with 'found' key."""
    from agent.tools.gitlab_tools import find_mr_for_commit

    result = await find_mr_for_commit("abc123")

    assert "found" in result


async def test_create_incident_issue_creates_real_issue():
    """create_incident_issue should create a GitLab issue and return its URL."""
    from agent.tools.gitlab_tools import create_incident_issue

    result = await create_incident_issue(
        title="[TEST] Incident Copilot automated test issue",
        service_name="test-service",
        root_cause_hypothesis="This is an automated test — safe to close.",
        evidence_summary="No real evidence. Generated by test suite.",
        suspect_commit_sha="",
        suspect_mr_url="",
        recommended_action="Close this issue — it was created by the test suite.",
    )

    assert "error" not in result, f"Issue creation failed: {result.get('error')}"
    assert "issue_iid" in result
    assert "web_url" in result
    assert "gitlab.com" in result["web_url"]
    assert isinstance(result["issue_iid"], int)


async def test_create_incident_issue_with_all_optional_fields():
    """create_incident_issue works with all optional fields populated."""
    from agent.tools.gitlab_tools import create_incident_issue

    result = await create_incident_issue(
        title="[TEST] Full fields test issue",
        service_name="payment-service",
        root_cause_hypothesis="NullPointerException in PaymentProcessor.charge() at line 42.",
        evidence_summary="15 NPE errors in last 5 min. Stack trace points to charge().",
        suspect_commit_sha="abc123def456",
        suspect_mr_url="https://gitlab.com/agent_gc/incident_copilot/-/merge_requests/1",
        recommended_action="git revert abc123def456 && kubectl rollout restart deploy/payment-service",
    )

    assert "error" not in result, f"Issue creation failed: {result.get('error')}"
    assert "web_url" in result
